### ISSUE TITLE
[BUG] UNKNOWN URL SCHEMA

### ISSUE THREAD

**Issue by brimwats** [LBF38/obsidian-syncthing-integration#105]
Here's a screenshot; I'm not sure why it is not understanding the URI (localhost is set correctly, as you can see un the settings)

![image](https://github.com/LBF38/obsidian-syncthing-integration/assets/73113656/6c4a2360-d01e-4879-8a31-9528e68b03e0)

**Comment by LBF38** [comment]
Yeah, I know that ahah ! It's in the making. I'm refactoring the address input to make it easier for me (dev) and for the user to enter the proper GUI listen address.

Here is a screenshot of what it would look like :
![image](https://github.com/LBF38/obsidian-syncthing-integration/assets/96347823/6e43b6e0-eb03-4b6d-a514-16011df10d1b)

It would be fixed by #103 .
Meanwhile, you have to add the full address format: `http://localhost:8384`. And see #102 for HTTPS support.

**Comment by brimwats** [comment]
no worries or pressure! just filling bugs out so you can track them! :)

**Comment by LBF38** [comment]
This should be resolved by the latest release. Please tell me if not.
